### ISSUE TITLE
New version cannot convert multi-DWI image, but old version can

### ISSUE THREAD

**Issue by cirongliu** [neurolabusc/Bru2Nii#12]
Hi, I noticed a problem with the update of the Bru2Nii,

All new versions  since 2017 cannot convert multi-DWI image correctly (6 b0 DWI image for example) (Fig.1):
![2](https://user-images.githubusercontent.com/3990516/28166904-ae0f172e-67a7-11e7-8b9e-a867d7b17482.png)

However, the old version (12Dec2016 : v1.0.20161212) are able to converted it well:
![1](https://user-images.githubusercontent.com/3990516/28167137-87590d5a-67a8-11e7-967a-744dc73da9b0.png)

I uploaded the data via in case u needed:
https://drive.google.com/file/d/0BzWRtQPhTYqBaHVDcGI5TkhOdFE/view?usp=sharing

Thanks!

**Comment by neurolabusc** [comment]
Hello, 
 Unfortunately, some Bruker files are stored on disk in the order X,Y,Z,T (spatial dimensions, then time) and others are stored X,Y,T,Z (2D images, time, then slices). I have looked, but I can not work out a way to determine how to detect this automatically. Indeed, images from the same series can use different methods. I do not have a Bruker system, but I suggest you contact them and ask them how they encode this information. Previously, I had thought the presence of a "d3proc" file indicated the slice and time dimensions needed to be swizzled, but your dataset provides a counter-example. To restore the old behavior change the lines
```  
  if BrHdr.has_d3proc_file then //based on one image from Mikaël Naveau 
    SwapDimsZT(p, ImgBytes, lNiHdr);   
```
to read
```  
  //if BrHdr.has_d3proc_file then //based on one image from Mikaël Naveau 
  //  SwapDimsZT(p, ImgBytes, lNiHdr);   
```
and recompile. Of course, this will fail on images with swizzled slices. Therefore, you may want to keep a copy compiled each way until the vendor suggests a solution. Perhaps @naveau has some ideas on whether this is specific to some sequences. It was his sequence `cyceron-dataset-T2RARE-DTISTANDARD` that exhibited both forms of storage from the same series, with a 'd3proc' file only found in the swizzled set.

**Comment by naveau** [comment]
I'm going for a long week-end right now but will have a look at this next week.
As far as I remember, the order of the data is described for each Bruker method in the application manual. I can probably introduce some conditions based on `ACQ_method`  to reorder the dimensions correctly.

> Indeed, images from the same series can use different methods.

I think that it depends on the post-processing applied by Bruker. I can imaging that derived dataset (like FA maps for DWI) are not ordered the same way than their original acquired data. I'll investigate this further and ask Bruker more details about that.

**Comment by naveau** [comment]
Some results about my morning investigations :

* the `d3proc` is indeed not an argument to swizzle slices. In fact, Paravision 5.1 seems to generate this file for all `reco` (see @insularcortex  example) while paravision 6+ only generate this file if the reconstruction is done using the old image viewer (which is the same as paravision 5). Unless the `d3proc` file is used at other part of the code it should not be use it as it may depends on the version of paravision.

* About 24c1a4509ce8a0da7f0e22ed927b123157643335 : the guess on 16/32 bits encoding does not work for derived dataset (the 2desq without reco file) because the dimension of the image is read from the reco file of the original data.

One workaround for the derived dataset would be :
* If the `reco` file does not exists, then read the `reco` file of the first reconstruction
* Overwrite the `BrkHdr` by the values read in the `visu_pars` file to get the correct informations :
  * `##$VisuCoreWordType` : `RECO_wordtype_bits`
  * `##$VisuCoreByteOrder` : `RECO_byte_order_little`
  * `##$VisuCoreFrameCount` : `ACQ_NI`
  * `##$VisuCoreSlicePacksSlices` : `ACQ_NSLICES`
  * `##$VisuCoreFrameCount` / `##$VisuCoreSlicePacksSlices` : `ACQ_NR`
It won't be perfect as I see that there are also specific offsets/slopes in the `visu_pars` file.

I think I derived too much from the original issue. To me, you probably should remove any swizzle based on the `d3proc` file (like you did in 24c1a4509ce8a0da7f0e22ed927b123157643335) to keep the original behavior and solve this issue.

About the derived dataset, maybe it not worth refactoring the code to get them reconstructed. I'll have a look at https://github.com/SebastianoF/bruker2nifti (that I discover reading your code). It seems that they base the reconstructions on the `visu_pars` files. If anything obvious comes to me I'll for sure send you a pull requests. In the meanwhile, the "Experimental support" for derived dataset is a good description of the state of the code !

**Comment by neurolabusc** [comment]
Thanks @naveau 
 1.) Is the selection between 16/32 bits encoding still required on modern Bruker datasets? I think this was a patch for ancient Bruker systems that would report 16-bits but were actually 32. I assume this is no longer required, and can be removed, right?
 2.) OK, so it sounds like automatic detection of swizzling is not possible. I guess we can add a command line option to set this.
 3.) Nice to know about bruker2nifti. Do tell me if you find any tricks they use.

**Comment by naveau** [comment]
> 1.) Is the selection between 16/32 bits encoding still required on modern Bruker datasets? I think this was a patch for ancient Bruker systems that would report 16-bits but were actually 32. I assume this is no longer required, and can be removed, right?

I did not have this encoding problem using Paravision 6+ but have no clue if it's still a problem in PV5.

> 2.) OK, so it sounds like automatic detection of swizzling is not possible. I guess we can add a command line option to set this.

Sounds reasonable as a first approach. In fact, detection is possible using the `visu_pars` file. I dig the documentation and found that :

> A data set can contain several Visu frames. Frame groups define an ordering and / or semantic for the frames. A good example is a multi slice multi echo (MSME) acquisition with 5 slices and 8 echoes. The data set contains 40 Visuframes (i.e. VisuCoreFrameCount = 40). [...]. The mapping is described in the VisuFrameOrderDesc parameter group. [...] The names of the dependant parameters for all frame groups is defined in VisuGroupDepVals - array of all frame group dependant parameter names. The indices of this array are referenced in VisuFGOrderDesc (attributes valsStart and valsCnt).

Here is an example in a DTI dataset having 30 slices and 67 diffusion experiments :
```
##$VisuFGOrderDescDim=2
##$VisuFGOrderDesc=( 2 )
(30, <FG_SLICE>, <>, 0, 2) (67, <FG_DIFFUSION>, <diffusion>, 2, 2)
##$VisuGroupDepVals=( 4 )
(<VisuCoreOrientation>, 0) (<VisuCorePosition>, 0) (<VisuFGElemComment>, 0) 
(<VisuAcqDiffusionBMatrix>, 0)
```

Each entry in `VisuFGOrderDesc` corresponds to a frame group, the last two integers of an entry refer to the associated dependent values (start and length of the selection in the `VisuGroupDepVals` array). E.g the `(30, <FG_SLICE>, <>, 0, 2)` has **2** dependents values starting at index **0** of the `VisuGroupDepVals` array : `(<VisuCoreOrientation>, 0) (<VisuCorePosition>, 0)`

I can send you the PV documentation if needed.

> 3.) Nice to know about bruker2nifti. Do tell me if you find any tricks they use.

Their approach is to preferentially use the `visu_pars` header as this file is explicitly described by Bruker as the parameter file needed for conversion purpose (Table 1.4, Document D-1-5) :

> Visu parameters for postprocessing, conversion, and display purposes

It might be interesting to parse this file at least to get :
* The frame group description (`VisuFGOrderDesc`) if it allows to decide how to swizzle the slices in case of 4D+ series
* The `VisuSeriesTypeId` : Type identifier of the series that differentiate original and derived dataset
> 1. For all series that describe an acquired data set the VisuSeriesTypeId
parameter value must begin with "ACQ_" (e.g. "ACQ_BRUKER_PVM" for data
sets acquired using a Bruker PVM method).
> 2. For all series that describe secondary derived data sets the VisuSeriesTypeId parameter value must begin with "DERIVED_" (e.g. "DERIVED_ISA" for parameter images created by the ISA tool).

A last remarks, the `d3procs` file seems to be deprecated and only produced by Paravision for 'legacy datasets' (e.g. ParaVisision 5.1) (Table 1.4, Document D-1-5).

**Comment by naveau** [comment]
Corrected typos : visu_parts -> visu_pars

**Comment by neurolabusc** [comment]
@insularcortex can you test the latest build. Tell me if you need me to compile for a specifc OS (just tell me if you want Windows, MacOS or Linux). If this works, we can close this issue and push a new release. Thanks @naveau for your work on this.

**Comment by cirongliu** [comment]
Thanks a lot for the update. I tested on different dataset with multiple images/echoes. It can successfully convert all different types. 

For the release, if possible to have the Linux version pre-compiled, just as the previous releases. 

Thanks again.

**Comment by naveau** [comment]
About multi-echo images. One should carefully check slice order cause they can be shuffled if there are multiple repetitions. Tested on the RARE and MSME multi-echo/multi-repetition sequences, [here](https://gitlab.com/naveau/bruker2nifti_qa/blob/50e316d3d7f710406aaae9a5183555b67045c9b6/raw/Cyceron_MultiEcho/20170720_080545_Lego_1_2.yml) you can find some dataset to test it.
I won't have time until end of August to double check this.

@neurolabusc  I think that you can release the current patch, mentioning that Bru2Nii does not fully support multi-echo reconstruction with repetitions.

**Comment by neurolabusc** [comment]
Slice order should be fixed now
