### ISSUE TITLE
bru2nii gives different output than pvconv+fslchfiletype

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/Bru2Nii#2]
I have a bruker series from an experiment over here, which I would like to analyze with FSL's `melodic`.

Depending on whether prior to `melodic` I convert the file to nifti via `pcvonv` and `fslchfiletype`:

```
pvconf -series 16
fslchfiletype NIFTI _16.img
melodic -i _16.nii -o pf16_melodic --report -v
```

or via bru2nii:

```
Bru2 -o bru2nii 16
melodic -i bru2nii16.nii -o bru2nii16_melodic --report -v
melodic -i bru2nii16.nii -o bru2nii16_melodic_10 --report -d 10 -v
```

I get different results: 10 components automatically from the first, and over 360 components from the second (see `pf16_melodic` and `bru2nii16_melodic` respectively). Of course I can restrict the number of components manually, which gives me 10 components from the bru2nii conversion as well, though these differ quite a bit.

I am trying to figure out what the difference between the files is, and which one is more "correct".
As it stands I think the header of the file converted with bru2nii looks more sane than what came out of pvconv and fslchfiletype. Could you also check and tell me what you think about the issue? Is there an easy way to copy the header (all the header and only the header) from one `.nii` file to another so we can check whether this is what is causing the great difference in behaviour with `melodic`?

All fies mentioned above (and the source needed to reproduce everything) are archived [here](http://chymera.eu/nie/bru2nii_melodic/bru2nii_melodic.tgz).

**Comment by neurolabusc** [comment]
Thanks for this example. The raw data is the same:
  hdr1 = spm_vol('_16.hdr');
  img1 = spm_read_vols(hdr1);
  hdr2 = spm_vol('bru2nii16.nii');
  img2 = spm_read_vols(hdr2);
  f = find(img1 ~= img2)
 "Empty matrix: 0-by-1"
However, fslhd reveals that pvconf does not insert the spatial matrix and bru2 missed the slice gap in your sequence. I suspect the latter explains the discrepancy, and this is fixed in the latest (11 Nov 2015) release. The Bruker format is both bizarre and poorly documented, so supporting all variations is a challenge.

As an aside:
 1.) While you demo was perfect for identifying the issue, in general you will want to motion-correct the data prior to using Melodic.
 2.) Your download included both a hdr/img pair and a in file with the same name. Be warned that this can cause FSL grief. It is a good idea to make sure that you never have files with the same name except different NIfTI file extensions in the same folder. For example "file.hdr", "file.nii" and "file.nii.gz" can all conflict with each other.
