### ISSUE TITLE
-f option descroption

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/Bru2Nii#4]
The Bru2 help tells me it has this option:

`-f force conversion of localizers images (multiple slice orientations)`
- are you sure you want to say "localizers images"? I think "localizer images" would be a better way to phrase it, as you are referring to a type of images: the localizer type.
- what does "(multiple slice orientations)" refer to?

**Comment by neurolabusc** [comment]
I have changed the text to read 
  -f force conversion of localizer images (multiple slice orientations)
In MRI the localizer scan is a quick set of orthogonal slices used to position the other images (some vendors used to refer to these as 'scout scans'. They are typically fast to acquire but are not used in subsequent analysis since they are 2D slices not 3D volumes. They pose a problem in NIfTI conversion as NIfTI requires all images in a sequence to have a single spatial transform, while localizer scans have three separate orientations (coronal, sagittal, axial) in a single sequence. Therefore, by default it is usually best to simply ignore these scans in conversion. However, for completeness my software allows you to convert these.

**Comment by TheChymera** [comment]
Got it ;)
